

CREATE TABLE app_users (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(50) UNIQUE NOT NULL,
    password    VARCHAR2(100) NOT NULL,
    role        VARCHAR2(20) CHECK (role IN ('ADMIN', 'HR', 'MANAGER'))
);
