-- Purpose: Create DEPARTMENTS table to store department info.

CREATE TABLE departments (
    department_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name    VARCHAR2(100) NOT NULL UNIQUE,
    location           VARCHAR2(100)
);
