-- CREATES A TABLE TO TRACK SALARY CHANGES OF EMPLOYEES
CREATE TABLE salary_history (
    history_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     NUMBER NOT NULL,
    old_salary      NUMBER(10,2),
    new_salary      NUMBER(10,2),
    change_date     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_emp_salary FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id)
);

